### ISSUE TITLE
trouble installing with - NPM install command

### ISSUE THREAD

**Issue by TRE8** [understrap/understrap-bs3#2]
When I run NPM install I get this message:

`npm WARN Invalid version: "0.3.9.5"`
`npm WARN understrap-bs3 No description`
`npm WARN understrap-bs3 No repository field.`
`npm WARN understrap-bs3 No README data`
`npm WARN understrap-bs3 No license field.`

The only way I can get the install to proceed is if I change the version number so it uses 3 numbers instead of 4.  I saved the version number to 0.3.9 and it worked, hopefully that doesn't mess anything up.

**Comment by holger1411** [comment]
If it works for you it is okay ;-)
